M48
; DRILL file {KiCad 9.0.6} date 2025-11-18T17:24:46-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-18T17:24:46-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.250
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X74.498Y-59.186
T2
X40.005Y-23.749
X40.005Y-64.516
X115.189Y-23.749
X115.189Y-64.389
M30
