M48
; DRILL file {KiCad 9.0.6} date 2025-11-16T23:41:58-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-16T23:41:58-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.250
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X143.26Y-90.5
T2
X113.665Y-56.515
X113.665Y-92.71
X189.23Y-56.515
X189.23Y-92.71
M30
